services:
  docker-proxy:
    image: alpine/socat
    # Ports must be exposed if you want to curl from the host
    ports:
      - "2375:2375"
    # Use 'entrypoint' to bypass potential Alpine shell wrapper issues
    entrypoint: ["/usr/bin/socat"]
    # The arguments must be provided as a list to avoid shell parsing errors
    command: ["-d", "-d", "TCP-LISTEN:2375,fork,reuseaddr", "UNIX-CONNECT:/var/run/docker.sock"]
    user: "0:1002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #networks:
     # - airflow